---
- name: starting and enabling docker
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: restarted
  listen: starting docker

- name: starting and enabling kubelet
  systemd:
    name: kubelet
    enabled: yes
    daemon_reload: yes
    state: restarted
  listen: starting kubernetes

- name: initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="192.168.100.10" --apiserver-cert-extra-sans="192.168.100.10"  --node-name k8s-master --pod-network-cidr=10.244.0.0/16
  listen: starting kubernetes

- name: deploy kubernetes dashboard
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml
  listen: starting kubernetes

- name: copy kubeconfig file to vagrant user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    mode: '0644'
    owner: vagrant
    group: vagrant
  listen: starting kubernetes

- name: fetch kubeconfig file to host machine
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: /tmp/vagrant-kubeconfig
    flat: yes
  listen: starting kubernetes

- name: generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  listen: starting kubernetes

- name: create join command file on master node
  copy:
    content: "{{ join_command.stdout_lines[0] }}"
    dest: /home/vagrant/.kube/join_command
    mode: '0644'
    owner: vagrant
    group: vagrant
  listen: starting kubernetes

- name: fetch join_command to ansible manager
  fetch:
    src: /home/vagrant/.kube/join_command
    dest: /tmp/join_command
    flat: yes
  listen: starting kubernetes
